  image: docker:git

  services:
    - docker:dind

  stages:
    - build
    - deploy

  build:
    stage: build
    script:
      - docker info
      - echo "${{ secrets.GITHUB_TOKEN }}" | docker login -ghcr.io -u ${{ github.actor }} --password-stdin ${{ env.REGISTRY }}
      - docker build ./ --tag ghcr.io/${{ github.repository }}:latest
      - docker push ${{ github.repository }}:latest
    only:
      - main

