
image: docker:git

services:
  - docker:dind

stages:
  - build
  - deploy

build:
  stage: build
  script:
    - docker info
    - echo "$CI_JOB_TOKEN" | docker login --username gitlab-ci-token --password-stdin $CI_REGISTRY
    - docker build ./ --tag $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_REF_NAME
  only:
    - main
    - develop

    deploy:
  stage: deploy
  before_script:
    - apk add --no-cache openssh-client  # Ставим SSH
    - mkdir -p ~/.ssh
    - chmod 700 ~/.ssh
    - echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
    - chmod 600 ~/.ssh/id_rsa
    - ssh-keyscan -H $SERVER_IP >> ~/.ssh/known_hosts
  script:
    - scp docker-compose.yml $SSH_USER@$SERVER_IP:/app/  # Копируем compose-файл
    - ssh $SSH_USER@$SERVER_IP "
        docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY &&
        docker-compose pull app &&  # Обновляем только app (остальное не трогаем)
        docker-compose down &&      # Останавливаем старые контейнеры
        docker-compose up -d        # Запускаем всё заново
      "
  only:
    - firstStage  # Деплоим только из main
